### ISSUE TITLE
Workflow pages needs content

### ISSUE THREAD

**Issue by rpovelones** [cuberis/standards#31]
https://cuberis.github.io/standards/pages/workflow

Combines:
- https://cuberis.github.io/standards/pages/git
- https://cuberis.github.io/standards/pages/setup

**Comment by andrewmarino** [comment]
We should include a section about Security for this or somewhere else in the docs...super important.

* 2FA your accounts.
* Use secure connections, SFTP/SSH (rather than regular FTP).
* Always use HTTPS, Let's Encrypt.
* Don't use commonly targeted usernames, `root`, `admin`, `webadmin`, etc...
